# Generated by Django 3.2.25 on 2024-04-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=200),
        ),
    ]
